/**
 * Forensic Relationship Types - Governance v6.0
 */
export const RelationshipTypes = {
    // HIGH PRIORITY: Forensic Lifecycle
    REVERSAL_OF: "REVERSAL_OF",
    CORRECTION_OF: "CORRECTION_OF",
    ADJUSTMENT_TO: "ADJUSTMENT_TO",
    SETTLEMENT_OF: "SETTLEMENT_OF",
    TRANSFER_TO: "TRANSFER_TO",
    CORROBORATES: "CORROBORATES",
    CONTRADICTS: "CONTRADICTS",

    // MEDIUM PRIORITY: Anomaly Detection
    DUPLICATE_PAYMENT: "POTENTIAL_DUPLICATE_PAYMENT",
    DUPLICATE_INVOICE: "POTENTIAL_DUPLICATE_INVOICE",
    UNUSUAL_OFFSET: "UNUSUAL_OFFSET",
    CIRCULAR_FLOW: "CIRCULAR_FLOW",

    // LOW PRIORITY: Classification
    SAME_VENDOR: "SAME_VENDOR",
    SAME_ACCOUNT: "SAME_ACCOUNT",
    SAME_CATEGORY: "SAME_CATEGORY",
    SAME_AMOUNT_RANGE: "SAME_AMOUNT_RANGE"
};

export const InvestigativePriority = {
    HIGH: "HIGH",
    MEDIUM: "MEDIUM",
    LOW: "LOW"
};
